---

routes:
  /:
    data: page.home
    template: home

  /blog/all/:
    controller: channel
    template: all_posts
    filter: 'tags:-hash-tag-content'

  /blog/tags/:
    template: list_topics
  /blog/projects/:
    template: list_projects
  /blog/series/:
    template: list_series

  /etc/adsb/:
    data: page.etc-adsb
    template: page
  /etc/clips/:
    data: page.etc-clips
    template: page
  /etc/published-elsewhere/:
    data: page.published-elsewhere
    template: page
  /etc/published-elsewhere/3d-printing/:
    data: page.published-elsewhere-3d-printing
    template: page

collections:
  /blog/:
    permalink: /blog/{year}/{month}/{slug}/
    template: index
    filter: 'tags:-hash-tag-content'

  /_stub/:
    permalink: /_stub/{slug}/
    template: post
    filter: 'tags:hash-tag-content'

taxonomies:
  tag: /blog/tag/{slug}/
