---

routes:
  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{year}/{slug}/
    template: index
    filter: 'tags:-hash-tag-content'

  /p/:
    permalink: /r/{slug}/
    template: post
    filter: 'tags:hash-tag-content'

taxonomies:
  tag: /tag/{slug}/
