---

routes:
  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{year}/{month}/{slug}/
    template: index
    filter: 'tags:-hash-tag-content'

  /_stub/:
    permalink: /_stub/{slug}/
    template: post
    filter: 'tags:hash-tag-content'

taxonomies:
  tag: /blog/tag/{slug}/


# TODO(cdzombak): /blog/tags
# TODO(cdzombak): /blog/projects
# TODO(cdzombak): /blog/series

# TODO(cdzombak): /etc/published-elsewhere
# TODO(cdzombak): /etc/clips
# TODO(cdzombak): /etc/adsb
# TODO(cdzombak): /etc/published-elsewhere/3d-printing/
