---
name: Deploy

"on":
  push:
    branches:
      - main

jobs:
  deploy-theme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Build
        run: |
          npm install --include=dev
          npm run zip
      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@a0ee1147d15641db25681e54549c4db9a53c2629
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: "gulpfile.js LICENSE README.md"
          theme-name: "dzombakdotcom"

  deploy-routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Routes
        run: |
          mkdir -p ${{ runner.temp }}/ghost

          curl -c ${{ runner.temp }}/ghost/cookie.txt \
            -d 'username=${{ secrets.GHOST_CI_USER }}' \
            -d 'password=${{ secrets.GHOST_CI_PASSWORD }}' \
            -H "Origin: ${{ secrets.GHOST_ADMIN_API_URL }}" \
            -H "Accept-Version: v3.0" \
            ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/api/admin/session/

          curl -b ${{ runner.temp }}/ghost/cookie.txt \
            -F "routes=@./routes.yaml" \
            -H "Accept-Version: v3.0" \
            -H "Origin: ${{ secrets.GHOST_ADMIN_API_URL }}" \
            ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/api/admin/settings/routes/yaml/

  deploy-redirects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Redirects
        run: |
          mkdir -p ${{ runner.temp }}/ghost

          curl -c ${{ runner.temp }}/ghost/cookie.txt \
            -d 'username=${{ secrets.GHOST_CI_USER }}' \
            -d 'password=${{ secrets.GHOST_CI_PASSWORD }}' \
            -H "Origin: ${{ secrets.GHOST_ADMIN_API_URL }}" \
            -H "Accept-Version: v3.0" \
            ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/api/admin/session/

          curl -b ${{ runner.temp }}/ghost/cookie.txt \
            -F "redirects=@./redirects.yaml" \
            -H "Accept-Version: v3.0" \
            -H "Origin: ${{ secrets.GHOST_ADMIN_API_URL }}" \
            ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/api/admin/redirects/upload/

  ntfy:
    name: Ntfy
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs: [deploy-theme, deploy-routes, deploy-redirects]
    steps:
      - name: Send success notification
        uses: niniyas/ntfy-action@9c6dc60073292f562769f83df2ace9f64ab31c78
        if: ${{ !contains(needs.*.result, 'failure') }}
        with:
          url: "https://ntfy.cdzombak.net"
          topic: "gha-builds"
          priority: 3
          headers: '{"authorization": "Bearer ${{ secrets.NTFY_TOKEN }}"}'
          tags: white_check_mark
          title: Ghost theme deployment succeeded
          details: Successfully deployed theme, routes, and redirects to Ghost.
      - name: Send failure notification
        uses: niniyas/ntfy-action@9c6dc60073292f562769f83df2ace9f64ab31c78
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          url: "https://ntfy.cdzombak.net"
          topic: "gha-builds"
          priority: 3
          headers: '{"authorization": "Bearer ${{ secrets.NTFY_TOKEN }}"}'
          tags: no_entry
          title: Ghost theme deployment failed
          details: Failed to deploy theme, routes, or redirects to Ghost.
